openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/danubetech/credential-issuer/0.0.1
info:
  description: This is an experimental open API specification for issuing digital credentials based on standards such as the Verifiable Credentials Data Model (https://www.w3.org/TR/vc-data-model/), JWT (https://tools.ietf.org/html/rfc7519), and Open Badges (https://openbadges.org/). Implementations are expected to change significantly and implementers that are not directly involved in the work are strongly urged to not implement this API. Implementations of this API may differ in terms of which data formats or proof formats they do or do not support. Implementations may choose to not support certain parts of this API (e.g. optional parts include changing and retrieving the status of a credential, or refreshing a credential). 
  version: "0.0.3"
  title: Credential Issuer API
  contact:
    email: markus@danubetech.com
  license:
    name: All documents in this Repository are licensed by contributors under the [W3C Software and Document License](http://www.w3.org/Consortium/Legal/copyright-software).
tags:
  - name: internal
    description: Internal APIs facing the Issuer.
  - name: public
    description: Public APIs facing the Holder and Verifier.
paths:
  /credentials:
    post:
      tags:
        - internal
      summary: Issues a credential and returns it in the response body.
      operationId: issueCredential
      description: Issues a credential and returns it in the response body. Support of this part of the API is REQUIRED for implementations.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueCredentialRequest'
        description: Parameters for issuing the credential.
      responses:
        '201':
          description: Credential successfully issued!
          content:
            application/json:
              schema:
                type: object
                description: The issued credential. This SHOULD include a reference or ID that can be used later for other parts of the API, e.g. changing and retrieving the status of the credential, or refreshing the credential.
        '400':
          description: invalid input!
        '500':
          description: error!
  /credentials/compose:
    post:
      tags:
        - internal
      summary: Composes a credential and returns it in the response body.
      operationId: composeCredential
      description: Composes a credential and returns it in the response body. Support of this part of the API is OPTIONAL for implementations.
      parameters:
        - in: query
          required: false
          name: templateReference
          schema:
            type: string
          description: Optional internal reference to a credential template. If this is present, it may be used to automatically pre-populate certain fields in the request body.
          example: 67466513-67a0-4812-8f26-995dd78c5aa6
        - in: query
          required: false
          name: subjectReference
          schema:
            type: string
          description: Optional internal reference to the subject for which to issue a credential. If this is present, it may be used to pre-populate certain fields in the request body (e.g. "claims" and/or "subject").
          example: 73b32334-81f3-4f4c-911e-710c7aadd4d8
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComposeCredentialRequest'
        description: Parameters for composing the credential.
      responses:
        '201':
          description: credential successfully composed!
          content:
            application/json:
              schema:
                type: object
                description: The composed credential. This composed credential can be issued by using the issue credential operation.
        '400':
          description: invalid input!
        '500':
          description: error!
  /credentials/{credentialReference}:
    get:
      tags:
        - internal
      summary: Retrieves a credential that has already been issued, and returns it in the response body.
      operationId: retrieveCredential
      description: Retrieves a credential that has already been issued, and returns it in the response body. The retrieved credential MUST be identical to the original credential when it was first issued. This can not be used for refreshing an expired credential. Support of this part of the API is OPTIONAL for implementations.
      parameters:
        - in: path
          required: true
          name: credentialReference
          schema:
            type: string
          description: Reference to a credential that has been issued.
      responses:
        '200':
          description: credential successfully retrieved!
          content:
            application/json:
              schema:
                type: object
                description: The retrieved credential.
        '400':
          description: invalid input!
        '404':
          description: credential not found!
        '500':
          description: error!
        '501':
          description: not supported by this implementation!
  /credentials/{credentialReference}/status:
    post:
      tags:
        - internal
      summary: Changes the credential status.
      operationId: changeCredentialStatus
      description: Changes the credential status. Support of this part of the API is OPTIONAL for implementations.
      parameters:
        - in: path
          required: true
          name: credentialReference
          schema:
            type: string
          description: Reference to a credential that has been issued.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeStatusRequest'
        description: Parameters for changing the credential status.
      responses:
        '200':
          description: credential status successfully changed!
        '400':
          description: invalid input!
        '404':
          description: credential not found!
        '500':
          description: error!
        '501':
          description: not supported by this implementation!
    get:
      tags:
        - public
      summary: Retrieves the credential status and returns it in the response body.
      operationId: retrieveCredentialStatus
      description: Retrieves the credential status and returns it in the response body. Support of this part of the API is OPTIONAL for implementations. WARNING - this type of "phone home" functionality is problematic from a privacy perspective, therefore this is likely to be removed in a future version.
      parameters:
        - in: path
          required: true
          name: credentialReference
          schema:
            type: string
          description: Reference to a credential that has been issued.
      responses:
        '200':
          description: credential status successfully retrieved!
          content:
            application/json:
              schema:
                type: object
                description: The credential status.
        '400':
          description: invalid input!
        '404':
          description: credential not found!
        '500':
          description: error!
        '501':
          description: not supported by this implementation!
  /credentials/{credentialReference}/refresh:
    post:
      tags:
        - public
      summary: Refreshes a credential and returns it in the response body.
      operationId: refreshCredential
      description: Refreshes a credential and returns it in the response body. Support of this part of the API is OPTIONAL for all implementations. WARNING - it may not make sense to model this functionality as a public API, instead the processes for "refreshing" may be more complex and use case specific, therefore this is likely to be removed in a future version.
      parameters:
        - in: path
          required: true
          name: credentialReference
          schema:
            type: string
          description: Reference to a credential that has been issued.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
        description: Parameters for refreshing the credential.
      responses:
        '200':
          description: credential successfully refreshed!
          content:
            application/json:
              schema:
                type: object
                description: The refreshed credential.
        '400':
          description: invalid input!
        '404':
          description: credential not found!
        '500':
          description: error!
        '501':
          description: not supported by this implementation!
components:
  schemas:
    IssueCredentialRequest:
      type: object
      properties:
        credential:
          type: object
          description: A JSON-LD Verifiable Credential without a proof.
          example: {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "https://www.w3.org/2018/credentials/examples/v1"
            ],
            "id": "http://example.gov/credentials/3732",
            "type": [
              "VerifiableCredential",
              "UniversityDegreeCredential"
            ],
            "issuer": "https://example.edu",
            "issuanceDate": "2020-03-11T23:09:06.803Z",
            "credentialSubject": {
              "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
              "degree": {
                "type": "BachelorDegree",
                "name": "Bachelor of Science and Arts"
              }
            }
          }
        options:
          type: object
          additionalProperties: false
          description: Options for specifying how the credential will be issued.
          properties:
            assertionMethod:
              type: string
              description: The URI of a key that will be used to issue the credential. If ommited a default assertionMethod will be used.
              example: "did:web:example.com#z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN"
    ComposeAndIssueCredentialRequest:
      type: object
      properties:
        issuer:
          type: string
          description: Optional identifier for the issuer of the credential. If this is missing, it may be pre-configured or implied by other values in the request.
          example: did:example:76e12ec712ebc6f1c221ebfeb1f
        subject:
          type: string
          description: Optional identifier for the subject of the credential. If this is missing, it may be pre-configured or implied by other values in the request, or there may not be an identifier for the subject of the credential.
          example: did:example:ebfeb1f712ebc6f1c276e12ec21
        types:
          type: array
          items:
            type: string
          description: Optional value for the type(s) of a credential. If this is missing, it may be pre-configured or implied by other values in the request.
          example: UniversityDegreeCredential
        issuanceDate:
          type: string
          format: date-time
          description: Optional value for the issuance date and time of the credential, to be used only when this value should not be automatically set to the current date and time.
          example: '2010-01-01T19:23:24Z'
        expirationDate:
          type: string
          format: date-time
          description: Optional value for the expiration date and time of the credential. If this is missing, it may be pre-configured or implied by other values in the request, or the credential may not have an expiration date and time.
          example: '2011-01-01T19:23:24Z'
        claims:
          type: object
          additionalProperties: true
          description: Optional object containing claims and their values.
          example: {"name": "Jayden Doe"}
        evidence:
          type: object
          additionalProperties: true
          description: Optional object containing evidence of the credential.
          example: {}
        termsOfUse:
          type: object
          additionalProperties: true
          description: Optional object containing terms of use of the credential.
          example: {}
        credentialFormat:
          type: string
          description: Optional value to specify the credential format. Well-known values are "jsonld", "jwt", "blockcerts". Other values MAY be supported. If this is missing, it may be pre-configured, and a default credential format will be used.
          example: jsonld
        proofFormat:
          type: string
          description: Optional value to specify the proof format. Well-known values are "ld-proof", "jws", "blockcerts". Other values MAY be supported. If this is missing, it may be pre-configured or implied by other values in the request (e.g. "credentialFormat"), and a default proof format will be used.
          example: jws
        credentialFormatOptions:
          type: object
          additionalProperties: true
          description: Optional object containing additional options specific to the chosen credential format. E.g. for the "jsonld" credential format, this could contain JSON-LD context(s) to be included in the credential.
          example: {"@context": "https://www.w3.org/2018/credentials/examples/v1"}
        proofFormatOptions:
          type: object
          additionalProperties: true
          description: Optional object containing additional options specific to the chosen proof format. E.g. for the "jws" proof format, this could specify a key identifier to be used for the proof.
          example: {"kid": "did:example:abfe13f712120431c276e12ecab#keys-1"}
    ChangeStatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          description: New status of the credential. Well-known values are "revoked", "suspended", "active". Other values MAY be supported.
          example: revoked
        reason:
          type: string
          description: Optional reason statement for the new status of the credential.
          example: Disciplinary action
        options:
          type: object
          additionalProperties: true
          description: Optional object containing additional options for the new status of the credential.
          example: {}
    RefreshRequest:
      type: object
      properties:
        options:
          type: object
          additionalProperties: true
          description: Optional object containing additional options for refreshing the credential.
          example: {}
